# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
stages:
- stage: 
  pool:
    vmImage: windows-latest
  jobs:
  - job: backend_build
    steps:
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'WebAPI/WebAPI.sln'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'WebAPI/WebAPI.sln'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'WebAPI/WebAPI.sln'
        configuration: Release
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'backend'
        publishLocation: 'Container'

- stage: 
  pool:
    vmImage: Ubuntu-latest
  jobs:
  - job: frontend_build
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'Asp.Net-Core-Web-API-and-Angular-7-CRUD/Angular7'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'Asp.Net-Core-Web-API-and-Angular-7-CRUD/Angular7'
        customCommand: 'run build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'frontend'
        publishLocation: 'Container'